fake_db = {
    "users": [{"id": 1, "email": "test@example.com"}],
    "firmwares": [
        {
            "id": 1,
            "name": "Audi A4 Stage 2",
            "price": 100,
            "car": "Audi A4 B8",
            "engine": "2.0 TFSI",
            "power": "+40 л.с.",
            "description": "Оптимизация топливных карт, увеличение мощности до 280 л.с.",
        },
        {
            "id": 2,
            "name": "BMW M3 Stage 1",
            "price": 150,
            "car": "BMW M3 E92",
            "engine": "4.0 V8",
            "power": "+30 л.с.",
            "description": "Корректировка углов зажигания, увеличение отклика на газ.",
        },
        {
            "id": 3,
            "name": "VW Golf Stage 3",
            "price": 200,
            "car": "VW Golf 7 R",
            "engine": "2.0 TSI",
            "power": "+80 л.с.",
            "description": "Полная прошивка с заменой калибровок турбины и впрыска. +80 л.с., +100 Нм.",
        },
        {
            "id": 4,
            "name": "Porsche 911 Stage 2",
            "price": 350,
            "car": "Porsche 911 Turbo",
            "engine": "3.8 Twin-Turbo",
            "power": "+60 л.с.",
            "description": "Оптимизация давления наддува, спортивные настройки DSG.",
        },
        {
            "id": 5,
            "name": "Mercedes C63 Stage 1",
            "price": 180,
            "car": "Mercedes C63 AMG",
            "engine": "6.2 V8",
            "power": "+35 л.с.",
            "description": "Увеличение отсечки по оборотам, изменение карт зажигания.",
        },
        {
            "id": 6,
            "name": "Subaru WRX Stage 2",
            "price": 170,
            "car": "Subaru WRX STI",
            "engine": "2.5 Turbo",
            "power": "+50 л.с.",
            "description": "Калибровка турбины, увеличенный угол опережения зажигания.",
        },
        {
            "id": 7,
            "name": "Ford Mustang Stage 3",
            "price": 250,
            "car": "Ford Mustang GT",
            "engine": "5.0 V8",
            "power": "+70 л.с.",
            "description": "Агрессивный калибровка, отключение ограничителя скорости, замена лямбда-зондов.",
        },
        {
            "id": 8,
            "name": "Toyota Supra Stage 1",
            "price": 220,
            "car": "Toyota Supra A90",
            "engine": "3.0 B58",
            "power": "+45 л.с.",
            "description": "Калибровка B58, увеличение наддува, корректировка впрыска.",
        },
        {
            "id": 9,
            "name": "Nissan GT-R Stage 2",
            "price": 400,
            "car": "Nissan GT-R R35",
            "engine": "3.8 V6 Twin-Turbo",
            "power": "+100 л.с.",
            "description": "Полный спектр калибровок для GR6, E85, замена MAF.",
        },
        {
            "id": 10,
            "name": "Audi RS6 Stage 1",
            "price": 300,
            "car": "Audi RS6 C8",
            "engine": "4.0 V8 TFSI",
            "power": "+80 л.с.",
            "description": "Прошивка 48V, увеличение мощности до 680 л.с.",
        },
        {
            "id": 11,
            "name": "BMW X5 M Stage 2",
            "price": 280,
            "car": "BMW X5 M F95",
            "engine": "4.4 V8",
            "power": "+60 л.с.",
            "description": "Прошивка DME, увеличение ограничителя, спортивный алгоритм переключений.",
        },
        {
            "id": 12,
            "name": "Kia Stinger Stage 1",
            "price": 130,
            "car": "Kia Stinger GT",
            "engine": "3.3 V6",
            "power": "+40 л.с.",
            "description": "Оптимизация турбин, изменение давления топлива.",
        },
        {
            "id": 13,
            "name": "Hyundai i30N Stage 2",
            "price": 160,
            "car": "Hyundai i30N",
            "engine": "2.0 T-GDI",
            "power": "+45 л.с.",
            "description": "Калибровка GDI, увеличение boost, корректировка зажигания.",
        },
        {
            "id": 14,
            "name": "Lexus IS F Stage 1",
            "price": 190,
            "car": "Lexus IS F",
            "engine": "5.0 V8",
            "power": "+20 л.с.",
            "description": "Корректировка VVTi, изменение карт зажигания для увеличения отклика.",
        },
        {
            "id": 15,
            "name": "Chevrolet Camaro Stage 3",
            "price": 260,
            "car": "Chevrolet Camaro SS",
            "engine": "6.2 V8",
            "power": "+75 л.с.",
            "description": "Замена калибровок для E85, отключение систем управления тягой.",
        },
    ],
}
